# Generated by Django 5.0.6 on 2024-05-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend_bistro', '0002_entrees_price_entrees_spice_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrees',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entrees',
            name='spice_level',
            field=models.IntegerField(default=0),
        ),
    ]
