# Generated by Django 5.0.6 on 2024-05-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend_bistro', '0005_menuitem_delete_apps_delete_entrees'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
